### ISSUE TITLE
Magento 2.4.6 compatibility?

### ISSUE THREAD

**Issue by bateaurouge** [dev-jq/Azkarra-Magento2-Theme-for-Core-Web-Vitals-and-SEO#1]
Hello,

I couldn't find anywhere to contact you directly.

Is this compatible with 2.4.6 currently? What needs to be updated for compatibility with future Magento versions?

Do you have recommendations for maintaining high core web vital scores when modifying the theme?

Thanks

**Comment by dev-jq** [comment]
Hi @bateaurouge

I will install and check on version 2.4.6, it will probably be fully compatible with what works for 2.4.5.
Are you interested in buying? then I can prioritize it and release it once with the final version 1.0.0 of Azkarra in the coming days.

The documentation for the template will contain information on how to maintain good WebVitals results, what to avoid, etc.
I try to supplement the document with questions that will arise from users during the implementation and adaptation of the template to their own needs.

Regards

**Comment by dev-jq** [comment]
Hi @bateaurouge

The Azkarra skin now works with Magento 2.4.6 as well. You can check DEMO. You can find the link in the repository description.
