### ISSUE TITLE
Errors on static-content:deploy. missing colour variables

### ISSUE THREAD

**Issue by gfxpixeldesigns** [dev-jq/Azkarra-Magento2-Theme-for-Core-Web-Vitals-and-SEO#2]
Getting errors compiling static content looking at the variables.less and colors.less they appear to be missing

e.g.

php bin/magento setup:static-content:deploy

Results in

Compilation from source: /home/user/public_html/lib/web/mage/gallery/gallery.less
variable @color-gray-darken3 is undefined in file /home/user/public_html/var/view_preprocessed/pub/static/frontend/jq-dev/my_azkarra/en_GB/css/source/lib/variables/_buttons.less in _buttons.less on line 37, column 24
35| @button__gradient-color-end: false;
36|
37| @button__hover__color: @color-gray-darken3;

Added a few to the variables manually but it keeps erroring on to the next missing variable and so on. Unsure how long it goes on for and whether you are working on this so i stopped there.

**Comment by dev-jq** [comment]
Hello,
I have a few questions to provide you with specific assistance:

1. What email address was used to purchase the Azkarra theme? I haven't received a request for an invitation to the private repository, where code fixes and new releases are uploaded (https://github.com/dev-jq/azkarra-premium)

2. Which version did you download and install? The latest is v1.0.5, and there was a previous fix for the Less compilation issue and missing variables. I want to know if this is a new problem or if you're using an older version.

**Comment by gfxpixeldesigns** [comment]
> Hello, I have a few questions to provide you with specific assistance:
> 
>     1. What email address was used to purchase the Azkarra theme? I haven't received a request for an invitation to the private repository, where code fixes and new releases are uploaded (https://github.com/dev-jq/azkarra-premium)
> 
>     2. Which version did you download and install? The latest is v1.0.5, and there was a previous fix for the Less compilation issue and missing variables. I want to know if this is a new problem or if you're using an older version.

This is the github repository version no versioning seems to be specified

**Comment by dev-jq** [comment]
**jq-dev/my_azzkarra** - THIS IS ONLY a example child theme.

You need the buy main template (parent): jq-dev/azzkarra, and the JqDev_AzkarraTheme module for this to work. **The code in the this public repo is just an example for previewing**.

**Comment by gfxpixeldesigns** [comment]
Okay understood i read it as a free and a paid version was hoping to test it out a little before making the purchase. I'll have a think about it but appreciate you getting back to me always nice to know theres support.

**Comment by dev-jq** [comment]
To test the functionality before purchasing, I have provided a DEMO with Magento 2.4.6.  For obvious reasons, you will receive the source code only after purchase. 

P.S.  I try to help in case of problems or any questions ;)
