### ISSUE TITLE
without attribute add to cart

### ISSUE THREAD

**Issue by pindrow** [dev-jq/Azkarra-Magento2-Theme-for-Core-Web-Vitals-and-SEO#3]
when click product "Affirm Water Bottle" add to cart from category page, moved in detail page, stop this redirection - added to card set from category page and home page

**Comment by dev-jq** [comment]
This report is unclear to me. You could describe it better.

**Comment by pindrow** [comment]
open this link https://m10454.app-on-demand.net/gear.html and click add to cart "Affirm Water Bottle" this button work 2 action same time 1. add to cart in the basket 2. move in detail page - only add to cat in the basket correct option from category page.
"if any customer want any product in the basket from the category page, customer can't add each time page moved in product detail page."

**Comment by dev-jq** [comment]
Hi @pindrow 

I fixed the error of redirecting to the product page after clicking add to cart (ajax) from the product list.
You can verify the fix on my demo.
**It will appear in the next version of Azkarra (v1.0.7 in March).**

However, you can see the corrected file (and implement it in your own project) in a private repository:
[github.com/dev-jq/azkarra-premium/commit](https://github.com/dev-jq/azkarra-premium/commit/d0cdafd3deea3c725ed0996c02cf71b5084f25b5)

Regards

**Comment by dev-jq** [comment]
Bug fixed since version 1.0.7 (March 1, 2024).
