### ISSUE TITLE
CheckoutCustomization php 8.2

### ISSUE THREAD

**Issue by pindrow** [dev-jq/Azkarra-Magento2-Theme-for-Core-Web-Vitals-and-SEO#4]
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property JqDev\CheckoutCustomization\Plugin\Block\Cart\Sidebar::$_scopeConfig is deprecated in /public_html/app/code/JqDev/CheckoutCustomization/Plugin/Block/Cart/Sidebar.php on line 31

**Comment by dev-jq** [comment]
Thank you for reporting the issue for PHP 8.2

**Comment by dev-jq** [comment]
Hey @pindrow 
in the private repository, [in this commit](https://github.com/dev-jq/azkarra-premium/commit/eb34bbf1be4f3b1ddce2094816b5768b6a7630a1) you will find **a fix for the Exception error in the JqDev_CheckoutCustomization module**.

The fix will officially appear in **Azkarra v1.0.8**

**Comment by dev-jq** [comment]
**Azkarra v1.0.8 just relased**. Bug fixed.
